name: Playwright Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build Next.js application
      run: npm run build
    - name: Start Next.js application
      run: npm start &
      background: true
    - name: Run Playwright tests
      run: npx playwright test
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-test-results
        path: tests-results/**/*
